// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package wboxproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IPv6 struct {
	High                 uint64   `protobuf:"fixed64,1,opt,name=high,proto3" json:"high,omitempty"`
	Low                  uint64   `protobuf:"fixed64,2,opt,name=low,proto3" json:"low,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPv6) Reset()         { *m = IPv6{} }
func (m *IPv6) String() string { return proto.CompactTextString(m) }
func (*IPv6) ProtoMessage()    {}
func (*IPv6) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *IPv6) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPv6.Unmarshal(m, b)
}
func (m *IPv6) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPv6.Marshal(b, m, deterministic)
}
func (m *IPv6) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPv6.Merge(m, src)
}
func (m *IPv6) XXX_Size() int {
	return xxx_messageInfo_IPv6.Size(m)
}
func (m *IPv6) XXX_DiscardUnknown() {
	xxx_messageInfo_IPv6.DiscardUnknown(m)
}

var xxx_messageInfo_IPv6 proto.InternalMessageInfo

func (m *IPv6) GetHigh() uint64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *IPv6) GetLow() uint64 {
	if m != nil {
		return m.Low
	}
	return 0
}

type Net4 struct {
	Addr                 uint32   `protobuf:"fixed32,1,opt,name=addr,proto3" json:"addr,omitempty"`
	PrefixLen            int32    `protobuf:"varint,2,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Net4) Reset()         { *m = Net4{} }
func (m *Net4) String() string { return proto.CompactTextString(m) }
func (*Net4) ProtoMessage()    {}
func (*Net4) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *Net4) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Net4.Unmarshal(m, b)
}
func (m *Net4) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Net4.Marshal(b, m, deterministic)
}
func (m *Net4) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Net4.Merge(m, src)
}
func (m *Net4) XXX_Size() int {
	return xxx_messageInfo_Net4.Size(m)
}
func (m *Net4) XXX_DiscardUnknown() {
	xxx_messageInfo_Net4.DiscardUnknown(m)
}

var xxx_messageInfo_Net4 proto.InternalMessageInfo

func (m *Net4) GetAddr() uint32 {
	if m != nil {
		return m.Addr
	}
	return 0
}

func (m *Net4) GetPrefixLen() int32 {
	if m != nil {
		return m.PrefixLen
	}
	return 0
}

type Net6 struct {
	Addr                 *IPv6    `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	PrefixLen            int32    `protobuf:"varint,2,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Net6) Reset()         { *m = Net6{} }
func (m *Net6) String() string { return proto.CompactTextString(m) }
func (*Net6) ProtoMessage()    {}
func (*Net6) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *Net6) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Net6.Unmarshal(m, b)
}
func (m *Net6) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Net6.Marshal(b, m, deterministic)
}
func (m *Net6) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Net6.Merge(m, src)
}
func (m *Net6) XXX_Size() int {
	return xxx_messageInfo_Net6.Size(m)
}
func (m *Net6) XXX_DiscardUnknown() {
	xxx_messageInfo_Net6.DiscardUnknown(m)
}

var xxx_messageInfo_Net6 proto.InternalMessageInfo

func (m *Net6) GetAddr() *IPv6 {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *Net6) GetPrefixLen() int32 {
	if m != nil {
		return m.PrefixLen
	}
	return 0
}

type Route4 struct {
	Dest                 *Net4    `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`
	Src                  uint32   `protobuf:"fixed32,2,opt,name=src,proto3" json:"src,omitempty"`
	Gateway              uint32   `protobuf:"fixed32,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route4) Reset()         { *m = Route4{} }
func (m *Route4) String() string { return proto.CompactTextString(m) }
func (*Route4) ProtoMessage()    {}
func (*Route4) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *Route4) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route4.Unmarshal(m, b)
}
func (m *Route4) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route4.Marshal(b, m, deterministic)
}
func (m *Route4) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route4.Merge(m, src)
}
func (m *Route4) XXX_Size() int {
	return xxx_messageInfo_Route4.Size(m)
}
func (m *Route4) XXX_DiscardUnknown() {
	xxx_messageInfo_Route4.DiscardUnknown(m)
}

var xxx_messageInfo_Route4 proto.InternalMessageInfo

func (m *Route4) GetDest() *Net4 {
	if m != nil {
		return m.Dest
	}
	return nil
}

func (m *Route4) GetSrc() uint32 {
	if m != nil {
		return m.Src
	}
	return 0
}

func (m *Route4) GetGateway() uint32 {
	if m != nil {
		return m.Gateway
	}
	return 0
}

type Route6 struct {
	Dest                 *Net6    `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`
	Src                  *IPv6    `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route6) Reset()         { *m = Route6{} }
func (m *Route6) String() string { return proto.CompactTextString(m) }
func (*Route6) ProtoMessage()    {}
func (*Route6) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *Route6) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route6.Unmarshal(m, b)
}
func (m *Route6) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route6.Marshal(b, m, deterministic)
}
func (m *Route6) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route6.Merge(m, src)
}
func (m *Route6) XXX_Size() int {
	return xxx_messageInfo_Route6.Size(m)
}
func (m *Route6) XXX_DiscardUnknown() {
	xxx_messageInfo_Route6.DiscardUnknown(m)
}

var xxx_messageInfo_Route6 proto.InternalMessageInfo

func (m *Route6) GetDest() *Net6 {
	if m != nil {
		return m.Dest
	}
	return nil
}

func (m *Route6) GetSrc() *IPv6 {
	if m != nil {
		return m.Src
	}
	return nil
}

// Message type byte: 1
type CfgSolict struct {
	// ed25519 public key of the client. MUST be 32 bytes.
	PeerPubkey           []byte   `protobuf:"bytes,1,opt,name=peer_pubkey,json=peerPubkey,proto3" json:"peer_pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CfgSolict) Reset()         { *m = CfgSolict{} }
func (m *CfgSolict) String() string { return proto.CompactTextString(m) }
func (*CfgSolict) ProtoMessage()    {}
func (*CfgSolict) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *CfgSolict) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CfgSolict.Unmarshal(m, b)
}
func (m *CfgSolict) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CfgSolict.Marshal(b, m, deterministic)
}
func (m *CfgSolict) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CfgSolict.Merge(m, src)
}
func (m *CfgSolict) XXX_Size() int {
	return xxx_messageInfo_CfgSolict.Size(m)
}
func (m *CfgSolict) XXX_DiscardUnknown() {
	xxx_messageInfo_CfgSolict.DiscardUnknown(m)
}

var xxx_messageInfo_CfgSolict proto.InternalMessageInfo

func (m *CfgSolict) GetPeerPubkey() []byte {
	if m != nil {
		return m.PeerPubkey
	}
	return nil
}

// Message type byte: 2
type Cfg struct {
	// The UNIX timestamp the configuration is valid until.
	ValidUntil uint64 `protobuf:"varint,2,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	// IPv6 network configuration.
	Net6    []*Net6   `protobuf:"bytes,3,rep,name=net6,proto3" json:"net6,omitempty"`
	Routes6 []*Route6 `protobuf:"bytes,4,rep,name=routes6,proto3" json:"routes6,omitempty"`
	// IPv4 network configuration.
	Net4    []*Net4   `protobuf:"bytes,16,rep,name=net4,proto3" json:"net4,omitempty"`
	Routes4 []*Route4 `protobuf:"bytes,17,rep,name=routes4,proto3" json:"routes4,omitempty"`
	// The WireGuard tunnel endpoint client should switch to.
	// Can be empty if the client should reuse the configuration tunnel.
	// tun6_endpoint - Publicly routable IPv6 address of server.
	// tun_endpoint  - Publicly routable IPv4 address of server.
	// (at least one should be non-empty)
	//
	// tun_port      - UDP port to use.
	Tun6Endpoint         *IPv6    `protobuf:"bytes,5,opt,name=tun6_endpoint,json=tun6Endpoint,proto3" json:"tun6_endpoint,omitempty"`
	Tun4Endpoint         uint32   `protobuf:"fixed32,18,opt,name=tun4_endpoint,json=tun4Endpoint,proto3" json:"tun4_endpoint,omitempty"`
	TunPort              uint32   `protobuf:"varint,6,opt,name=tun_port,json=tunPort,proto3" json:"tun_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cfg) Reset()         { *m = Cfg{} }
func (m *Cfg) String() string { return proto.CompactTextString(m) }
func (*Cfg) ProtoMessage()    {}
func (*Cfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *Cfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cfg.Unmarshal(m, b)
}
func (m *Cfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cfg.Marshal(b, m, deterministic)
}
func (m *Cfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cfg.Merge(m, src)
}
func (m *Cfg) XXX_Size() int {
	return xxx_messageInfo_Cfg.Size(m)
}
func (m *Cfg) XXX_DiscardUnknown() {
	xxx_messageInfo_Cfg.DiscardUnknown(m)
}

var xxx_messageInfo_Cfg proto.InternalMessageInfo

func (m *Cfg) GetValidUntil() uint64 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func (m *Cfg) GetNet6() []*Net6 {
	if m != nil {
		return m.Net6
	}
	return nil
}

func (m *Cfg) GetRoutes6() []*Route6 {
	if m != nil {
		return m.Routes6
	}
	return nil
}

func (m *Cfg) GetNet4() []*Net4 {
	if m != nil {
		return m.Net4
	}
	return nil
}

func (m *Cfg) GetRoutes4() []*Route4 {
	if m != nil {
		return m.Routes4
	}
	return nil
}

func (m *Cfg) GetTun6Endpoint() *IPv6 {
	if m != nil {
		return m.Tun6Endpoint
	}
	return nil
}

func (m *Cfg) GetTun4Endpoint() uint32 {
	if m != nil {
		return m.Tun4Endpoint
	}
	return 0
}

func (m *Cfg) GetTunPort() uint32 {
	if m != nil {
		return m.TunPort
	}
	return 0
}

// Message type byte: 3
type Nack struct {
	// Human-readable error description.
	Description          []byte   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nack) Reset()         { *m = Nack{} }
func (m *Nack) String() string { return proto.CompactTextString(m) }
func (*Nack) ProtoMessage()    {}
func (*Nack) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{7}
}

func (m *Nack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nack.Unmarshal(m, b)
}
func (m *Nack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nack.Marshal(b, m, deterministic)
}
func (m *Nack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nack.Merge(m, src)
}
func (m *Nack) XXX_Size() int {
	return xxx_messageInfo_Nack.Size(m)
}
func (m *Nack) XXX_DiscardUnknown() {
	xxx_messageInfo_Nack.DiscardUnknown(m)
}

var xxx_messageInfo_Nack proto.InternalMessageInfo

func (m *Nack) GetDescription() []byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func init() {
	proto.RegisterType((*IPv6)(nil), "IPv6")
	proto.RegisterType((*Net4)(nil), "Net4")
	proto.RegisterType((*Net6)(nil), "Net6")
	proto.RegisterType((*Route4)(nil), "Route4")
	proto.RegisterType((*Route6)(nil), "Route6")
	proto.RegisterType((*CfgSolict)(nil), "CfgSolict")
	proto.RegisterType((*Cfg)(nil), "Cfg")
	proto.RegisterType((*Nack)(nil), "Nack")
}

func init() {
	proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0)
}

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0xd5, 0x25, 0x6d, 0xe8, 0xcb, 0x86, 0x86, 0x2f, 0x78, 0x07, 0x44, 0x08, 0x97, 0x0a,
	0x4d, 0x3d, 0x80, 0x15, 0x09, 0x89, 0x03, 0x62, 0xe2, 0x80, 0x84, 0x46, 0x65, 0xc4, 0x85, 0x4b,
	0x94, 0x26, 0x6e, 0x66, 0x2d, 0xb2, 0x23, 0xc7, 0x59, 0xb7, 0x7f, 0x82, 0xbf, 0x19, 0xbd, 0xd7,
	0xb4, 0xc9, 0x81, 0x03, 0xa7, 0xbc, 0xfc, 0xde, 0xf7, 0x7d, 0xf9, 0x62, 0x19, 0x9e, 0xb7, 0xce,
	0x7a, 0x5b, 0xda, 0x66, 0x4d, 0x43, 0x7a, 0x0d, 0xe1, 0xb7, 0xcd, 0x43, 0xc6, 0x18, 0x84, 0x77,
	0xba, 0xbe, 0xe3, 0xb3, 0x64, 0xb6, 0x5a, 0x48, 0x9a, 0xd9, 0x25, 0x04, 0x8d, 0xdd, 0xf3, 0x33,
	0x42, 0x38, 0xa6, 0x1f, 0x21, 0xbc, 0x55, 0x5e, 0xa0, 0xba, 0xa8, 0x2a, 0x47, 0xea, 0x48, 0xd2,
	0xcc, 0x5e, 0x01, 0xb4, 0x4e, 0xed, 0xf4, 0x63, 0xde, 0x28, 0x43, 0xa6, 0xb9, 0x5c, 0x1e, 0xc8,
	0x77, 0x65, 0xd2, 0xcf, 0x64, 0xcd, 0xd8, 0xd5, 0xc4, 0x1a, 0xbf, 0x9f, 0xaf, 0xf1, 0xeb, 0xff,
	0x97, 0xf0, 0x03, 0x16, 0xd2, 0xf6, 0x5e, 0x09, 0xcc, 0xa8, 0x54, 0xe7, 0x4f, 0x19, 0xd8, 0x49,
	0x12, 0xc2, 0xce, 0x9d, 0x2b, 0xc9, 0x1c, 0x49, 0x1c, 0x19, 0x87, 0xa8, 0x2e, 0xbc, 0xda, 0x17,
	0x4f, 0x3c, 0x20, 0x7a, 0x7c, 0x4d, 0x3f, 0x0d, 0x81, 0xd9, 0xbf, 0x02, 0xb3, 0x21, 0xf0, 0xe5,
	0x18, 0x78, 0xaa, 0x8b, 0x24, 0xbd, 0x86, 0xe5, 0xcd, 0xae, 0xfe, 0x69, 0x1b, 0x5d, 0x7a, 0xf6,
	0x1a, 0xe2, 0x56, 0x29, 0x97, 0xb7, 0xfd, 0xf6, 0x5e, 0x3d, 0x51, 0xce, 0xb9, 0x04, 0x44, 0x1b,
	0x22, 0xe9, 0x9f, 0x33, 0x08, 0x6e, 0x76, 0x35, 0x0a, 0x1f, 0x8a, 0x46, 0x57, 0x79, 0x6f, 0xbc,
	0x6e, 0x28, 0x36, 0x94, 0x40, 0xe8, 0x17, 0x12, 0xac, 0x62, 0x94, 0xcf, 0x78, 0x90, 0x04, 0x93,
	0x2a, 0x88, 0xd8, 0x1b, 0x88, 0x1c, 0xf6, 0xed, 0x32, 0x1e, 0xd2, 0x36, 0x5a, 0x1f, 0xfa, 0xcb,
	0x23, 0x1f, 0xdc, 0x82, 0x5f, 0x8e, 0x6e, 0x41, 0x6e, 0x31, 0xba, 0x05, 0x7f, 0x31, 0x75, 0x8b,
	0xa3, 0x5b, 0xb0, 0x77, 0x70, 0xe1, 0x7b, 0x93, 0xe5, 0xca, 0x54, 0xad, 0xd5, 0xc6, 0xf3, 0xf9,
	0xf4, 0xaf, 0xcf, 0x71, 0xf7, 0x75, 0x58, 0xb1, 0xb7, 0xa4, 0x15, 0xa3, 0x96, 0xd1, 0xe1, 0xa2,
	0x48, 0x9c, 0x44, 0x57, 0xf0, 0xcc, 0xf7, 0x26, 0x6f, 0xad, 0xf3, 0x7c, 0x91, 0xcc, 0x56, 0x17,
	0x32, 0xf2, 0xbd, 0xd9, 0x58, 0xe7, 0xd3, 0x15, 0x84, 0xb7, 0x45, 0x79, 0xcf, 0x12, 0x88, 0x2b,
	0xd5, 0x95, 0x4e, 0xb7, 0x5e, 0x5b, 0x33, 0x9c, 0xdc, 0x14, 0x7d, 0x89, 0x7f, 0x2f, 0xf7, 0x5b,
	0xfb, 0x48, 0xf7, 0x75, 0xbb, 0xa0, 0xc7, 0x87, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x53,
	0xfd, 0x36, 0xc8, 0x02, 0x00, 0x00,
}
